export enum Errors {
	AlreadyEnrolled = "AlreadyEnrolled",
	DefaultRoleNotFound = "DefaultRoleNotFound",
	EmailSendError = "EmailSendError",
	EmailTaken = "EmailTaken",
	EnrollmentExpired = "EnrollmentExpired",
	InvalidRequestBody = "InvalidRequestBody",
	NoSchemaProvidedInPolicyConfig = "NoSchemaProvidedInPolicyConfig",
	NotFound = "NotFound",
	PasswordThreeDollars = "PasswordThreeDollars",
	PaymentAlreadyPaid = "PaymentAlreadyPaid",
	PaymentExpired = "PaymentExpired",
	PaymentNotFound = "PaymentNotFound",
	RegisterDisabled = "RegisterDisabled",
	UnknownError = "UnknownError",
	UserExists = "UserExists",
	UserNotFound = "UserNotFound",
	UserNotConfirmed = "UserNotConfirmed",
	ValidationError = "ValidationError",
}
