export const errors = {
	policies: {
		noSchemaInConfig: "noSchemaInConfig",
		bodyNotValid: "bodyNotValid",
	},
	missingCourseId: "missingCourseId",
	courseNotFound: "courseNotFound",
	emailAlreadyExisting: "emailAlreadyExisting",
	alreadyEnrolled: "alreadyEnrolled",
	pastDeadline: "pastDeadline",
	userNotCreated: "userNotCreated",
	badPolicyConfig: "badPolicyConfig",
	defaultRoleNotFound: "defaultRoleNotFound",
	emailSendError: "emailSendError",
	emailTaken: "emailTaken",
	enrollmentExpired: "enrollmentExpired",
	internalServerError: "internalServerError",
	invalidRequestBody: "invalidRequestBody",
	invalidRole: "invalidRole",
	missingCourseID: "missingCourseID",
	missingUserInfo: "missingUserInfo",
	noSchemaProvidedInPolicyConfig: "noSchemaProvidedInPolicyConfig",
	notFound: "notFound",
	passwordThreeDollars: "passwordThreeDollars",
	paymentAlreadyConfirmed: "paymentAlreadyConfirmed",
	paymentAlreadyExecuted: "paymentAlreadyExecuted",
	paymentExpired: "paymentExpired",
	paymentNotFound: "paymentNotFound",
	registerDisabled: "registerDisabled",
	unknownError: "unknownError",
	userExists: "userExists",
	userNotConfirmed: "userNotConfirmed",
	userNotFound: "userNotFound",
	validationError: "validationError",
};
