export const errors = {
	policies: {
		noSchemaInConfig: "noSchemaInConfig",
		bodyNotValid: "bodyNotValid",
	},
	courseNotFound: "courseNotFound",
	// AlreadyEnrolled: "AlreadyEnrolled",
	// BadPolicyConfig: "BadPolicyConfig",
	// DefaultRoleNotFound: "DefaultRoleNotFound",
	// EmailSendError: "EmailSendError",
	// EmailTaken: "EmailTaken",
	// EnrollmentExpired: "EnrollmentExpired",
	// InternalServerError: "InternalServerError",
	// InvalidRequestBody: "InvalidRequestBody",
	// InvalidRole: "InvalidRole",
	// MissingCourseID: "MissingCourseID",
	// MissingUserInfo: "MissingUserInfo",
	// NoSchemaProvidedInPolicyConfig: "NoSchemaProvidedInPolicyConfig",
	// NotFound: "NotFound",
	// PasswordThreeDollars: "PasswordThreeDollars",
	// PaymentAlreadyConfirmed: "PaymentAlreadyConfirmed",
	// PaymentAlreadyPaid: "PaymentAlreadyPaid",
	// PaymentExpired: "PaymentExpired",
	// PaymentNotFound: "PaymentNotFound",
	// RegisterDisabled: "RegisterDisabled",
	// UnknownError: "UnknownError",
	// UserExists: "UserExists",
	// UserNotConfirmed: "UserNotConfirmed",
	// UserNotFound: "UserNotFound",
	// ValidationError: "ValidationError",
};
